### ISSUE TITLE
code to remove

### ISSUE THREAD

**Issue by Andyauk** [ST4LTH/qb-multicharacter#1]
`server_scripts { '@mysql-async/lib/MySQL.lua' }server_scripts { '@mysql-async/lib/MySQL.lua' }server_scripts { '@mysql-async/lib/MySQL.lua' }`

needs removing part of the [stupid shit code] as you called it. in fxmanifest

keep up the good work

**Comment by ST4LTH** [comment]
Fixed and Thanks!
