### ISSUE TITLE
Character slot

### ISSUE THREAD

**Issue by gringoDiaz** [ST4LTH/qb-multicharacter#2]
Not an issue but a question mate, do you know how to fix this when trying to limit players to only have 1 character the user slot stretch like this one. anyways thank you for the great script!
![Untitled](https://user-images.githubusercontent.com/63420825/200148348-2d2e3254-aa4c-46a6-b196-fe2866f96e56.png)

**Comment by ST4LTH** [comment]
Well i kind of made this script to be 4 char only but i guess u could use a "max-width:" in the css to limit how long it can be

**Comment by gringoDiaz** [comment]
ohhh i see, i'll try to make a max-width and see if it will work. anyways bro thank you!! nice work bro

**Comment by xxUnknown13xx** [comment]
> you
Let me know the measurements if you done it please :)
